import './globals.css'
import type { Metadata } from 'next'
import { Inter, Borel, Preahvihear } from 'next/font/google'

const preahvihear = Preahvihear({ weight: "400", subsets: ["latin"] })
// const borel = Borel({ weight: "400", subsets: ["latin"] })
// const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Next.js Todo App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${preahvihear.className} bg-slate-400 text-white container mx-auto p-4`}>{children}</body>
    </html>
  )
}
